apiVersion: v1
kind: ConfigMap
metadata:
  name: recsys-config
  namespace: recsys
data:
  MOVIELENS_PATH: "./data/raw/ml-1m"
  MODELS: "./data/models"

  MODEL_TYPE: "als"
  MODEL_NAME: "alternating_least_squares.npz"
  SOURCE: "csv"
  RATING_THRESHOLD: "4"
  PROJECT_ID: "movielens-recsys-484717"
  MODEL_BUCKET: "${PROJECT_ID}-recsys-models"
  RAW_BUCKET: "${PROJECT_ID}-recsys-raw"