apiVersion: v1
kind: ConfigMap
metadata:
  name: recsys-config
  namespace: recsys
data:
  MOVIELENS_PATH: "./data/raw/ml-1m"
  MODELS: "./data/models"

  MODEL_TYPE: "als"
  MODEL_NAME: "alternating_least_squares.npz"
  SOURCE: "db"
  RATING_THRESHOLD: "4"
  PROJECT_ID: "movielens-recsys-484717"
  DB_HOST: 127.0.0.1
  DB_PORT: 5432
  DB_NAME: recsys
  DB_USER: recsys_app
