apiVersion: v1
kind: Secret
metadata:
  name: recsys-db-secret
  namespace: recsys
type: Opaque
stringData:
  DB_USER: "recsys_app"
  DB_PASSWORD: "{{ db_password }}"
  DB_NAME: "recsys"
  CLOUDSQL_CONNECTION_NAME: "{{ cloudsql_connection_name }}"