apiVersion: v1
kind: Service
metadata:
  name: recsys-api
  namespace: recsys
spec:
  type: LoadBalancer
  selector:
    app: recsys-api
  ports:
    - name: http
      port: 80
      targetPort: 8000